server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: redevable-route
          uri: lb://REDEVABLE-SERVICE
          predicates:
            - Path=/redevable/**
          filters:
            - RewritePath=/microservice1/(?<path>.*), /$\{path}
        - id: categorie-route
          uri: lb://CATEGORIE-SERVICE
          predicates:
            - Path=/categorie/**
          filters:
            - RewritePath=/microservice2/(?<path>.*), /$\{path}
        - id: terrain-route
          uri: lb://TERRAIN-SERVICE
          predicates:
            - Path=/terrain/**
            - Path=/taxe/**